DOT_Ksiega_gosci/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DOT_Ksiega_gosci.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace DOT_Ksiega_gosci.Controllers
{
    public class ManagementController : Controller
    {
        private ManagementModel db = new ManagementModel();

        // GET: Management
        public ActionResult UserList()
        {
            if (User.Identity.IsAuthenticated)
            {
                var uM = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

                List<UserListViewModel> model = new List<UserListViewModel>();
                foreach (var user in db.AspNetUsers.ToList())
                {
                    UserListViewModel userView = new UserListViewModel();

                    userView.Id = user.Id;
                    userView.Login = user.UserName;
                    List<String> listRole = uM.GetRoles(user.Id).ToList();
                    userView.Role = string.Join(",", listRole);
                    model.Add(userView);
                }

                return View(model);
            }
            else
                return RedirectToAction("Login", "Account");
        }
        public ActionResult EditUser(string id)
        {
            if (User.Identity.IsAuthenticated)
            {
                UserEditViewModel model = new UserEditViewModel();
                var uM = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

                ViewBag.RoleId = new SelectList(db.AspNetRoles, "Name", "Name");
                model.roles = uM.GetRoles(id).ToList();
                model.Id = id;
                model.UserName = db.AspNetUsers.FirstOrDefault(x => x.Id == id).UserName;
                return View(model);
            }
            else
                return RedirectToAction("Login", "Account");
        }
        [HttpPost]
       // [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult EditUser(UserEditViewModel model, string[] selectedRoles)
        {
            var uM = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));

            if (User.Identity.IsAuthenticated) // if the user is already logged in
            {

                try
                {



                    var UserToUpdate = db.AspNetUsers.Find(model.Id);




                    var roles = uM.GetRoles(model.Id).ToArray();
                    uM.RemoveFromRoles(model.Id, roles);
                    uM.AddToRoles(model.Id, selectedRoles);

                    return RedirectToAction("UserList");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }


            // If we got this far, something failed, redisplay form
            return View(model);
        }
        // GET: Management/Delete/5
        public ActionResult DeleteUser(string id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                AspNetUsers aspNetUsers = db.AspNetUsers.Find(id);
                if (aspNetUsers == null)
                {
                    return HttpNotFound();
                }
                return View(aspNetUsers);
            }
            else
                return RedirectToAction("Login", "Account");

        }

        // POST: Management/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUsers aspNetUsers = db.AspNetUsers.Find(id);

            foreach (var role in db.AspNetUserRoles.Where(x => x.UserId == id))
                db.AspNetUserRoles.Remove(role);
            db.AspNetUsers.Remove(aspNetUsers);
            db.SaveChanges();
            return RedirectToAction("UserList");
        }

        public ActionResult RoleList()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View(db.AspNetRoles.OrderBy(x => x.Id).ToList());
            }
            else
                return RedirectToAction("Login", "Account");

        }

        // GET: AspNetRoles/Create
        public ActionResult CreateRole()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
                return RedirectToAction("Login", "Account");

        }

        // POST: AspNetRoles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateRole([Bind(Include = "Id,Name")] AspNetRoles aspNetRoles)
        {
            if (!String.IsNullOrEmpty(aspNetRoles.Name))
            {
                aspNetRoles.Id = (Convert.ToInt32(db.AspNetRoles.OrderByDescending(x => x.Id).First().Id) + 1).ToString();
                db.AspNetRoles.Add(aspNetRoles);
                db.SaveChanges();
                return RedirectToAction("RoleList");
            }


            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Edit/5
        public ActionResult EditRole(string id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
                if (aspNetRoles == null)
                {
                    return HttpNotFound();
                }
                return View(aspNetRoles);
            }
            else
                return RedirectToAction("Login", "Account");

        }

        // POST: AspNetRoles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult EditRole([Bind(Include = "Id,Name")] AspNetRoles aspNetRoles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetRoles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("RoleList");
            }
            return View(aspNetRoles);
        }

        // GET: AspNetRoles/Delete/5
        public ActionResult DeleteRole(string id)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
                if (aspNetRoles == null)
                {
                    return HttpNotFound();
                }
                return View(aspNetRoles);
            }
            else
                return RedirectToAction("Login", "Account");

        }

        // POST: AspNetRoles/Delete/5
        [HttpPost, ActionName("DeleteRole")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteRoleConfirmed(string id)
        {
            AspNetRoles aspNetRoles = db.AspNetRoles.Find(id);
            db.AspNetRoles.Remove(aspNetRoles);
            db.SaveChanges();
            return RedirectToAction("RoleList");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DOT_Ksiega_gosci/Views/Management/CreateRole.cshtml
@model DOT_Ksiega_gosci.Models.AspNetRoles



<h2>Dodaj Rolę</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dodaj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wróć", "RoleList",null,new { @class = "btn btn-default" })
</div>

DOT_Ksiega_gosci/Views/Management/DeleteRole.cshtml
@model DOT_Ksiega_gosci.Models.AspNetRoles

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń Role   @Html.DisplayFor(model => model.Name)</h2>

<div>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

	</dl>

	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Usuń" class="btn btn-danger" />
			</div>
		</div>
		
	}
</div>
<div>
	@Html.ActionLink("Wróć", "RoleList", null, new { @class = "btn btn-default" })


</div>

DOT_Ksiega_gosci/Views/Management/DeleteUser.cshtml
@model DOT_Ksiega_gosci.Models.AspNetUsers

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń Użytkownika @Model.UserName</h2>


<div>
    <hr />
    <dl class="dl-horizontal">
     
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

	<div class="form-actions no-color">
		@Html.ActionLink("Wróć", "UserList", null, new { @class = "btn btn-default" })

		<input type="submit" value="Delete" class="btn btn-danger" />
	</div>
    }
</div>

DOT_Ksiega_gosci/Views/Management/EditRole.cshtml
@model DOT_Ksiega_gosci.Models.AspNetRoles

<h2>Edytuj Nazwę Roli</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

	<div>
		@Html.ActionLink("Wróć", "RoleList", null, new { @class = "btn btn-default" })

	</div>

DOT_Ksiega_gosci/Views/Management/EditUser.cshtml
@model DOT_Ksiega_gosci.Models.UserEditViewModel

@{
	ViewBag.Title = "Edit";
}

<h2>Edycja ról dla użytkownika   @Html.DisplayFor(model => model.UserName)</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">

	@Html.HiddenFor(x => x.Id, Model.Id)
	@foreach (var role in (SelectList)ViewBag.RoleId)
	{

		
		
			if (Model.roles.Any(role.Value.Contains))
			{

				<input type="checkbox" name="SelectedRoles" value="@role.Value" class="checkbox-inline" checked />
				@Html.Label(role.Value, new { @class = "control-label" })<br />
			}
			else
			{
				<input type="checkbox" name="SelectedRoles" value="@role.Value" class="checkbox-inline" />
				@Html.Label(role.Value, new { @class = "control-label" })<br />
			}
		

	}
	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Zapisz" class="btn btn-default" />
		</div>
	</div>
</div>
}
	<div>
		@Html.ActionLink("Wróć", "UserList",null,new { @class="btn btn-default"})
	</div>

DOT_Ksiega_gosci/Views/Management/LayoutManagement.cshtml
<center>
	<h2>Menu</h2>
</center>

<p>@Html.ActionLink("Użytkownicy", "UserList", "Management",null, new { @class = "btn btn-default btn-lg btn-block" })</p>
<p>@Html.ActionLink("Role", "RoleList", "Management",null, new { @class = "btn btn-default btn-lg btn-block" })</p>

DOT_Ksiega_gosci/Views/Management/RoleList.cshtml
@model IEnumerable<DOT_Ksiega_gosci.Models.AspNetRoles>

@{
	ViewBag.Title = "Role";
}

<div class="col-md-3">
	@Html.Partial("~/Views/Management/LayoutManagement.cshtml")

</div>
<div class="col-md-9">
	<h2>Role</h2>

	<p style="text-align:right">
		@Html.ActionLink("Dodaj Role", "CreateRole",null, new { @class = "btn btn-primary" })
	</p>
	<table class="table">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Id)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>

			<th></th>
		</tr>

		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Id)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td style="text-align:right">
					@Html.ActionLink("Edytuj", "EditRole", new { id = item.Id }, new { @class = "btn btn-default" }) 
					@Html.ActionLink("Usuń", "DeleteRole", new { id = item.Id }, new { @class = "btn btn-danger" })
				</td>
			</tr>
		}

	</table>
	</div>

DOT_Ksiega_gosci/Views/Management/UserList.cshtml
@model IEnumerable<DOT_Ksiega_gosci.Models.UserListViewModel>

@{
	ViewBag.Title = "Użytkownicy";
}

<div class="col-md-3">
	@Html.Partial("~/Views/Management/LayoutManagement.cshtml")

</div>
<div class="col-md-9">
	<h2>Użytkownicy</h2>
	<p style="text-align:right">
		@Html.ActionLink("Dodaj Użytkownika", "Register", "Account",null, new { @class = "btn btn-primary" })
	</p>
	<table class="table">
		<tr>

			<th>
				@Html.DisplayNameFor(model => model.Login)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Role)
			</th>
			<th></th>
		</tr>

		@foreach (var item in Model)
		{
		<div ><tr>

			<td>
				@Html.DisplayFor(modelItem => item.Login)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Role)
			</td>
			<td style="text-align:right">
				@Html.ActionLink("Edytuj", "EditUser", new { id = item.Id }, new { @class = "btn btn-default" })
				@Html.ActionLink("Usuń", "DeleteUser", new { id = item.Id }, new { @class = "btn btn-danger" })
			</td>
		</tr></div>
		}

	</table>
</div>